

development:
  adapter: mysql
  port: 3307
  encoding: utf8
  database: family_development
  username: root 
  password: 
  host: localhost
  

production:
  adapter: mysql
  port: 3307
  encoding: utf8
  database: family_production
  username: root 
  password: 
  host: localhost
